services:
  - type: web
    name: lawgg-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: ASSEMBLY_API_KEY
        value: a3fada8210244129907d945abe2beada
      - key: PYTHON_VERSION
        value: 3.9.16
